# Generated by Django 3.2.7 on 2022-01-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
