# Generated by Django 3.2.7 on 2022-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_auto_20220106_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='Congregation', max_length=50),
            preserve_default=False,
        ),
    ]
