# Generated by Django 3.2.7 on 2022-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0009_auto_20220115_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
