# Generated by Django 3.2.7 on 2022-01-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0010_alter_member_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='baptised',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=5, null=True),
        ),
    ]
