# Generated by Django 3.2.7 on 2022-02-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0012_auto_20220206_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
